project:
  type: website

website:
  title: "Prasanna Paithankar"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Research.qmd
      - Projects.qmd
      - Misc.qmd
      # - Blog.qmd
      - href: Assets/Resume_Prasanna_Paithankar.pdf
        icon: bi-filetype-pdf
        text: CV
      - icon: github
        href: https://github.com/PrasannaPaithankar/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



