---
title: "Dabble Wabble"
---
<style>
  p {
    text-align: justify;
  }

  a {
    color: #007bff;
    /* color: inherit; */
    text-decoration: none;
  }
</style>
<hr>

<a href="Blogs/Compilers-Interpreters.html" style="color: inherit; text-decoration: none;">

### Compilers & Interpreters
We experimentally demonstrate a high-entropy source based on the intensity fluctuation in a femtosecond laser. The setup successfully passes statistical tests without any post-processing. The generator can be potentially used for quantum communication and cryptography.
</a>

<a href="Blogs/Operating-Systems.html" style="color: inherit; text-decoration: none;">

### Operating Systems
lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
</a>

<a href="Blogs/Hobby-Electronics.html" style="color: inherit; text-decoration: none;">

### Hobby Electronics
lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
</a>

<hr>
<div style="font-size: 12px; color: grey; text-align: right; ">
Prasanna Paithankar | Deptarment of Computer Science & Engineering | Indian Insitute of Technology Kharagpur<br>Made using [Quarto](https://quarto.org/) </div>