# Quantum Optics {.unnumbered}

<div style="text-align: justify">

### Free Field Quantization
#### Quantization of single mode electromagnetic field
Maxwell's equations:
$$\nabla \cdot \vec{E} = 0$$
$$\nabla \cdot \vec{B} = 0$$
$$\nabla \times \vec{E} = -\frac{\partial \vec{B}}{\partial t}$$
$$\nabla \times \vec{B} = \mu_0 \epsilon_0 \frac{\partial \vec{E}}{\partial t}$$
<br><br> where $\vec{E} = \vec{E}(\vec{r}, t)\ ;\ \vec{B} = \vec{B}(\vec{r}, t)$

Field polarization along x-axis:
$$\vec{E} = E_x(z, t) \hat{x}\ $$

Single mode field:
$$ \vec{E} = \vec{E}(z, t) = \sqrt{\frac{\hbar \omega}{2 \epsilon_0 V}} q(t)\sin(kz) \hat{x}\ $$

where $q(t)$ has dimensions of length, $V$ is the volume of the cavity and $\omega_m = cm\pi/L$ where $c$ is the speed of light. Also

$$ \vec{B} = \vec{B}(z, t) = \frac{\mu_0\epsilon_0}{k}\sqrt{\frac{\hbar \omega}{2 \epsilon_0 V}}\ p(t)\cos(kz) \hat{y}\ $$

where $p(t) = \dot{q}(t)$ has dimensions of momentum.

We can write the Hamiltonian of the field as:

$$ H = \frac{1}{2} \int_V dV (\epsilon_0 E^2 + \frac{1}{\mu_0} B^2) = \frac{1}{2}(p^2 + \omega^2 q^2) $$
         

#### 1D Harmonic Oscillator
The Hamiltonian of a 1D harmonic oscillator is given by:

$$ H = \frac{1}{2}(p^2 + \omega^2 q^2) $$

where $p$ and $q$ are the momentum and position of the classical oscillator.

#### Quantization of 1D Harmonic Oscillator
$$q\rightarrow \hat{q}\ ;\ p\rightarrow \hat{p}$$

we have the commutation relation:
$$ [\hat{q}, \hat{p}] = i\hbar $$

The Hamiltonian of the 1D quantum harmonic oscillator is given by:

$$ \hat{H} = \frac{1}{2}(\hat{p}^2 + \omega^2 \hat{q}^2) $$
where $\hat{p}, \hat{q}$ are Hermitian operators.

### Creation and Annihilation Operators
The creation and annihilation operators are defined as:

$$ \hat{a} = \frac{1}{\sqrt{2\hbar\omega}} (\omega \hat{q} + i\hat{p}) $$
$$ \hat{a}^\dagger = \frac{1}{\sqrt{2\hbar\omega}} (\omega \hat{q} - i\hat{p}) $$

The operators are non-Hermitian.

also
$$ \hat{q} = \sqrt{\frac{\hbar}{2\omega}} (\hat{a} + \hat{a}^\dagger) $$
$$ \hat{p} = i\sqrt{\frac{\hbar\omega}{2}} (\hat{a}^\dagger - \hat{a}) $$

The commutation relation is given by:

$$ [\hat{a}, \hat{a}^\dagger] = 1 $$

Putting the above relations in previous equation we get:

$$ \hat{E_x} = \sqrt{\frac{\hbar \omega}{\epsilon_0 V}} (\hat{a} + \hat{a}^\dagger) \sin(kz) $$
$$ \hat{B_y} = \sqrt{\frac{\hbar \omega}{\epsilon_0 V}} (\hat{a}^\dagger - \hat{a}) \cos(kz) $$

where $\mathcal{E} = \sqrt{\frac{\hbar \omega}{\epsilon_0 V}}, \mathcal{B} = \sqrt{\frac{\hbar \omega}{\epsilon_0 V}}$ are the field per photon.

The Hamiltonian of the field is given by:

$$ \hat{H} = \frac{1}{2}(\hat{p}^2 + \omega^2 \hat{q}^2) = \hbar \omega (\hat{a}^\dagger \hat{a} + \frac{1}{2}) $$

### Evolution of the Field
The time evolution of the field is given by:

$$ i\hbar \frac{\partial}{\partial t}\hat{a} = [\hat{a}, \hat{H}] $$
$$ \implies \frac{\partial}{\partial t}\hat{a} = -i\omega \hat{a} $$

The solution of the above equation is given by:

$$ \hat{a}(t) = \hat{a}(0) e^{-i\omega t} $$
$$ \hat{a}^\dagger(t) = \hat{a}^\dagger(0) e^{i\omega t} $$

$$\hat{E_x} = \mathcal{E}(\hat{a}(0)e^{-i\omega t} + \hat{a}^\dagger(0)e^{i\omega t}) \sin(kz)$$

### Fock States
The Fock states are the eigenstates of the number operator $\hat{a}^\dagger \hat{a}$.

$$ \hat{a}^\dagger \hat{a} |n\rangle = n |n\rangle $$ 
where $n$ is the number of photons in the state $|n\rangle$ and $\hat{a}^\dagger \hat{a} = n$ is the photon number operator in the mode.

</div>